spring:
  profiles:
    active: dev

---
server:
  port: 8501
spring:
  profiles: test
  application:
    name: microservicecloud-test


---
server:
  port: 8502
spring:
  profiles: dev
  application:
    name: microservicecloud-dev
