spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-test


---
server:
  port: 8002
spring:
  profiles: dev
  application:
    name: microservicecloud-dev
